ARG CI_IMAGE_REGISTRY

FROM ${CI_IMAGE_REGISTRY}/oci-kube-ci:1.0.5 as builder

ARG COMPONENT

ENV SRC /go/src/github.com/oracle/oci-cloud-controller-manager
ENV GOVERSION "go1.16"

RUN yum install which -y
RUN yum install bison -y
RUN curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer -o /bin/gvm-installer
RUN sh /bin/gvm-installer
#RUN echo "source /root/.gvm/scripts/gvm" >> /etc/bashrc
RUN source /root/.gvm/scripts/gvm && gvm install $GOVERSION

ENV GOPATH /go/
RUN mkdir -p /go/bin $SRC
ADD . $SRC

WORKDIR $SRC

RUN source /root/.gvm/scripts/gvm && gvm use $GOVERSION && ARCH=arm make clean build-arm-all

FROM arm64v8/oraclelinux:7-slim

RUN yum install -y util-linux \
  && yum install -y e2fsprogs \
  && yum clean all
 \

COPY --from=0 /go/src/github.com/oracle/oci-cloud-controller-manager/dist/arm/* /usr/local/bin/
